services:
  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: reviewplatform
      POSTGRES_DB: product-service
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
